openapi: 3.0.3
info:
  version: 2021 03 22
  title: Payment Methods
  description: 'Payment Method storage is the Global Payments service where sensitive information is securely stored in exchange for a Global Payments unique identifier. This identifier, commonly referred to as a token, is then used to create Sale and Refund Transactions.'
  contact:
    name: API Integrations
    url: 'https://developer.globalpay.com/?gp-api=true'
    email: api.integrations@globalpay.com
  x-gp-yaml-file-version: 1
servers:
  - url: 'https://apis.sandbox.globalpay.com/ucp'
    description: Sandbox Environment
  - url: 'https://apis.globalpay.com/ucp'
    description: Production Environment
paths:
  /payment-methods:
    post:
      tags:
        - Create
      summary: Create Payment Method
      description: Create a stored payment method on the Global Payments system and return a unique Global Payments ID  that can be used to create future Sale or Refund Transactions.
      operationId: post-payment-method
      parameters:
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/Content-type'
        - $ref: '#/components/parameters/X-GP-Version'
        - $ref: '#/components/parameters/X-GP-Idempotency'
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Updatedcreaterequest'
            examples:
              Store a Card:
                value:
                  reference: CustABC_Card_1
                  usage_mode: MULTIPLE
                  card:
                    number: '4263970000005262'
                    expiry_month: '05'
                    expiry_year: '25'
                    cvv: '233'
              Create Single Use Token:
                value:
                  reference: CustABC_Card_1
                  usage_mode: SINGLE
                  card:
                    number: '4263970000005262'
                    expiry_month: '05'
                    expiry_year: '25'
                    cvv: '233'
              Create a Network Token:
                value:
                  reference: CustABC_Card_1
                  first_name: Jane
                  last_name: Doe
                  usage_mode: USE_NETWORK_TOKEN
                  card:
                    number: '4622943123052988'
                    expiry_month: '12'
                    expiry_year: '25'
                    cvv: '291'
              Create a Token Associated With a Payer:
                value:
                  account_name: Tokenization
                  reference: CustABC_Card_10
                  fingerprint_mode: ALWAYS
                  name: John's payment method
                  payer:
                    id: PYR_84fd9c9c07c442339cee215d974819b5
                  card:
                    number: '4263970000005262'
                    expiry_month: '05'
                    expiry_year: '25'
                    cvv: '852'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateResponse'
        '400':
          $ref: '#/components/responses/RequestInvalid_400'
        '401':
          $ref: '#/components/responses/AuthenticationInvalid_401'
        '403':
          $ref: '#/components/responses/NotAuthorized_403'
        '404':
          description: Resource Not Found
        '500':
          $ref: '#/components/responses/ServerError_500'
        '501':
          $ref: '#/components/responses/UnknownServerError_501'
        '502':
          $ref: '#/components/responses/UnknownPlatformError_502'
        '504':
          $ref: '#/components/responses/ServerTimeout_504'
      security:
        - bearerAuth: []
      servers:
        - url: 'https://apis.sandbox.globalpay.com/ucp'
          description: Sandbox Environment
        - url: 'https://apis.globalpay.com/ucp'
          description: Production Environment
    get:
      tags:
        - List Payment Methods
      summary: List Payment Methods
      description: Return a list of stored payment methods.
      operationId: get-payment-methods
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/page_size'
        - $ref: '#/components/parameters/order'
        - $ref: '#/components/parameters/order_by'
        - $ref: '#/components/parameters/reference'
        - $ref: '#/components/parameters/status'
        - $ref: '#/components/parameters/from_time_created'
        - $ref: '#/components/parameters/to_time_created'
        - $ref: '#/components/parameters/from_time_last_updated'
        - $ref: '#/components/parameters/to_time_last_updated'
        - name: id
          in: query
          schema:
            $ref: '#/components/schemas/id_PAYMENT_METHODS.id'
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/Content-type'
        - $ref: '#/components/parameters/X-GP-Version'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListResponse'
        '400':
          $ref: '#/components/responses/RequestInvalid_400'
        '401':
          $ref: '#/components/responses/AuthenticationInvalid_401'
        '403':
          $ref: '#/components/responses/NotAuthorized_403'
        '404':
          description: Resource Not Found
        '500':
          $ref: '#/components/responses/ServerError_500'
        '501':
          $ref: '#/components/responses/UnknownServerError_501'
        '502':
          $ref: '#/components/responses/UnknownPlatformError_502'
        '504':
          $ref: '#/components/responses/ServerTimeout_504'
      security:
        - bearerAuth: []
      servers:
        - url: 'https://apis.sandbox.globalpay.com/ucp'
          description: Sandbox Environment
        - url: 'https://apis.globalpay.com/ucp'
          description: Production Environment
  '/payment-methods/{id}':
    get:
      tags:
        - Get a Payment Method
      summary: Get a Payment Method
      description: Return a single view of a stored payment method.
      operationId: get-payment-methods-id
      parameters:
        - $ref: '#/components/parameters/id'
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/Content-type'
        - $ref: '#/components/parameters/X-GP-Version'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetResponse'
        '400':
          $ref: '#/components/responses/RequestInvalid_400'
        '401':
          $ref: '#/components/responses/AuthenticationInvalid_401'
        '403':
          $ref: '#/components/responses/NotAuthorized_403'
        '404':
          description: Resource Not Found
        '500':
          $ref: '#/components/responses/ServerError_500'
        '501':
          $ref: '#/components/responses/UnknownServerError_501'
        '502':
          $ref: '#/components/responses/UnknownPlatformError_502'
        '504':
          $ref: '#/components/responses/ServerTimeout_504'
      security:
        - bearerAuth: []
      servers:
        - url: 'https://apis.sandbox.globalpay.com/ucp'
          description: Sandbox Environment
        - url: 'https://apis.globalpay.com/ucp'
          description: Production Environment
    patch:
      tags:
        - Edit a Payment Method
      summary: Edit a Payment Method
      description: Change information about a stored payment method such as update the card expiry date or the funding type of card or the bank identifier of the account number.
      operationId: patch-payment-methods-id
      parameters:
        - $ref: '#/components/parameters/id'
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/Content-type'
        - $ref: '#/components/parameters/X-GP-Version'
        - $ref: '#/components/parameters/X-GP-Idempotency'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchRequest'
            examples:
              Edit a Stored Card:
                value:
                  name: John's payment method
                  card:
                    number: '4263970000005262'
                    expiry_month: '05'
                    expiry_year: '25'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatchResponse'
        '400':
          $ref: '#/components/responses/RequestInvalid_400'
        '401':
          $ref: '#/components/responses/AuthenticationInvalid_401'
        '403':
          $ref: '#/components/responses/NotAuthorized_403'
        '404':
          description: Resource Not Found
        '500':
          $ref: '#/components/responses/ServerError_500'
        '501':
          $ref: '#/components/responses/UnknownServerError_501'
        '502':
          $ref: '#/components/responses/UnknownPlatformError_502'
        '504':
          $ref: '#/components/responses/ServerTimeout_504'
      security:
        - bearerAuth: []
      servers:
        - url: 'https://apis.sandbox.globalpay.com/ucp'
          description: Sandbox Environment
        - url: 'https://apis.globalpay.com/ucp'
          description: Production Environment
    delete:
      tags:
        - Delete a Payment Method
      summary: Delete a Payment Method
      description: Delete a stored payment method.
      operationId: delete-payment-methods-id
      parameters:
        - $ref: '#/components/parameters/id'
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/Content-type'
        - $ref: '#/components/parameters/X-GP-Version'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    $ref: '#/components/schemas/id_PAYMENT_METHODS.id'
                  status:
                    $ref: '#/components/schemas/status_PAYMENT_METHODS.status'
                  action:
                    type: object
                    properties:
                      id:
                        $ref: '#/components/schemas/id_PAYMENT_METHODS.action.id'
                      type:
                        $ref: '#/components/schemas/type_PAYMENT_METHODS.action.type'
                      time_created:
                        $ref: '#/components/schemas/time_created_PAYMENT_METHODS.action.time_created'
                      result_code:
                        $ref: '#/components/schemas/result_code_PAYMENT_METHODS.action.result_code'
                      app_id:
                        $ref: '#/components/schemas/app_id_PAYMENT_METHODS.action.app_id'
                      app_name:
                        $ref: '#/components/schemas/app_name_PAYMENT_METHODS.action.app_name'
        '400':
          $ref: '#/components/responses/RequestInvalid_400'
        '401':
          $ref: '#/components/responses/AuthenticationInvalid_401'
        '403':
          $ref: '#/components/responses/NotAuthorized_403'
        '404':
          description: Resource Not Found
        '500':
          $ref: '#/components/responses/ServerError_500'
        '501':
          $ref: '#/components/responses/UnknownServerError_501'
        '502':
          $ref: '#/components/responses/UnknownPlatformError_502'
        '504':
          $ref: '#/components/responses/ServerTimeout_504'
      security:
        - bearerAuth: []
      servers:
        - url: 'https://apis.sandbox.globalpay.com/ucp'
          description: Sandbox Environment
        - url: 'https://apis.globalpay.com/ucp'
          description: Production Environment
  '/payment-methods/{id}/detokenize':
    post:
      tags:
        - Detokenize a Payment Method
      summary: Detokenize a Payment Method
      description: Detokenize the stored payment method to get a full payment method information.(Availability in production depends on your live configuration.)
      operationId: post-payment-methods-id-detokenize
      parameters:
        - $ref: '#/components/parameters/id'
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/Content-type'
        - $ref: '#/components/parameters/X-GP-Version'
        - $ref: '#/components/parameters/X-GP-Idempotency'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Detokenize'
        '400':
          $ref: '#/components/responses/RequestInvalid_400'
        '401':
          $ref: '#/components/responses/AuthenticationInvalid_401'
        '403':
          $ref: '#/components/responses/NotAuthorized_403'
        '404':
          description: Resource Not Found
        '500':
          $ref: '#/components/responses/ServerError_500'
        '501':
          $ref: '#/components/responses/UnknownServerError_501'
        '502':
          $ref: '#/components/responses/UnknownPlatformError_502'
        '504':
          $ref: '#/components/responses/ServerTimeout_504'
      security:
        - bearerAuth: []
      servers:
        - url: 'https://apis.sandbox.globalpay.com/ucp'
          description: Sandbox Environment
        - url: 'https://apis.globalpay.com/ucp'
          description: Production Environment
  /payment-methods/search:
    post:
      tags:
        - Search for a Payment Method
      summary: Search for a Payment Method
      description: Return a list of stored payment methods where search criteria is in the message body.
      operationId: post-payment-methods-search
      parameters:
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/Content-type'
        - $ref: '#/components/parameters/X-GP-Version'
        - $ref: '#/components/parameters/X-GP-Idempotency'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchRequest'
            examples:
              Search for a Payment Method:
                value:
                  account_name: Tokenization
                  card:
                    number: '4263970000005262'
                    expiry_month: '05'
                    expiry_year: '25'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'
        '400':
          $ref: '#/components/responses/RequestInvalid_400'
        '401':
          $ref: '#/components/responses/AuthenticationInvalid_401'
        '403':
          $ref: '#/components/responses/NotAuthorized_403'
        '404':
          description: Resource Not Found
        '500':
          $ref: '#/components/responses/ServerError_500'
        '501':
          $ref: '#/components/responses/UnknownServerError_501'
        '502':
          $ref: '#/components/responses/UnknownPlatformError_502'
        '504':
          $ref: '#/components/responses/ServerTimeout_504'
      security:
        - bearerAuth: []
      servers:
        - url: 'https://apis.sandbox.globalpay.com/ucp'
          description: Sandbox Environment
        - url: 'https://apis.globalpay.com/ucp'
          description: Production Environment
tags:
  - name: Create
  - name: Edit a Payment Method
  - name: Get a Payment Method
  - name: List Payment Methods
components:
  parameters:
    page:
      name: page
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/page.paging.page'
    page_size:
      name: page_size
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/page_size.paging.page_size'
    order:
      name: order
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/order.paging.order'
    order_by:
      name: order_by
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/order_by.paging.order_by'
    reference:
      name: reference
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/reference_PAYMENT_METHODS.reference'
    status:
      name: status
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/status_PAYMENT_METHODS.status'
    from_time_created:
      name: from_time_created
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/from_time_created'
    to_time_created:
      name: to_time_created
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/to_time_created'
    from_time_last_updated:
      name: from_time_last_updated
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/from_time_last_updated'
    to_time_last_updated:
      name: to_time_last_updated
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/to_time_last_updated'
    id:
      name: id
      in: path
      description: Unique Global Payments generated id used to reference a stored payment method on the Global Payments system. Often referred to as the payment method token. This value can be used instead of payment method details such as a card number and expiry date.
      required: true
      schema:
        type: string
        example: PMT_f5bbdfde-3010-4802-8f5d-1cdb2a2381c2
      examples:
        default:
          value: PMT_f5bbdfde-3010-4802-8f5d-1cdb2a2381c2
    Authorization:
      name: Authorization
      in: header
      description: Bearer access token value used to authorize and access the API.  Must always begin with the string "Bearer".
      required: true
      schema:
        type: string
        default: Bearer DCKbRy6gtN6gWJI2ja0B7e3POtbb
        example: Bearer DCKbRy6gtN6gWJI2ja0B7e3POtbb
    Content-type:
      name: Content-type
      in: header
      description: Format of the message body.
      required: true
      schema:
        type: string
        default: application/json
        example: application/json
    X-GP-Version:
      name: X-GP-Version
      in: header
      description: The version of the API to execute the request.
      required: true
      schema:
        type: string
        minLength: 1
        maxLength: 50
        default: '2021-03-22'
        example: '2021-03-22'
    X-GP-Idempotency:
      name: X-GP-Idempotency
      in: header
      description: Integrator generated value submitted in the request header that is checked to ensure the same value has not been seen in the last 24 hours. It is used to ensure idempotency is maintained with this action.
      required: false
      schema:
        type: string
        minLength: 1
        maxLength: 50
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  responses:
    RequestInvalid_400:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/objRequestInvalid_400'
    AuthenticationInvalid_401:
      description: Not Authenticated
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AuthenticationInvalid_401'
    NotAuthorized_403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotAuthorized_403'
    ServerError_500:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ServerError_500'
    UnknownServerError_501:
      description: Not implemented
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UnknownServerError_501'
    UnknownPlatformError_502:
      description: Bad Gateway
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UnknownPlatformError_502'
    ServerTimeout_504:
      description: Timeout
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ServerTimeout_504'
  schemas:
    Updatedcreaterequest:
      type: object
      title: CreateRequest
      properties:
        account_name:
          $ref: '#/components/schemas/account_name_PAYMENT_METHODS.account_name'
        reference:
          $ref: '#/components/schemas/reference_PAYMENT_METHODS.reference'
        usage_mode:
          $ref: '#/components/schemas/usage_mode_PAYMENT_METHODS.usage_mode'
        fingerprint_mode:
          $ref: '#/components/schemas/fingerprint_mode_PAYMENT_METHODS.fingerprint_mode'
        name:
          $ref: '#/components/schemas/name_PAYMENT_METHODS.name'
        payer:
          type: object
          properties:
            id:
              $ref: '#/components/schemas/id_PAYMENT_METHODS.payer.id'
        card:
          type: object
          properties:
            number:
              $ref: '#/components/schemas/number_PAYMENT_METHODS.card.number'
            expiry_month:
              $ref: '#/components/schemas/expiry_month_PAYMENT_METHODS.card.expiry_month'
            expiry_year:
              $ref: '#/components/schemas/expiry_year_PAYMENT_METHODS.card.expiry_year'
            cvv:
              $ref: '#/components/schemas/cvv_PAYMENT_METHODS.card.cvv'
            brand_reference:
              $ref: '#/components/schemas/brand_reference_PAYMENT_METHODS.card.brand_reference'
          required:
            - number
            - expiry_month
            - expiry_year
      required:
        - reference
        - card
    account_name_PAYMENT_METHODS.account_name:
      type: string
      description: A meaningful label for the merchant account set by Global Payments.
      minLength: 1
      maxLength: 50
      example: Tokenization
    reference_PAYMENT_METHODS.reference:
      type: string
      description: Merchant defined field to uniquely reference the stored payment method.
      minLength: 1
      maxLength: 50
      example: CustABC_Card_1
    usage_mode_PAYMENT_METHODS.usage_mode:
      type: string
      enum:
        - SINGLE
        - MULTIPLE
        - USE_CARD_NUMBER
        - USE_NETWORK_TOKEN
      description: |
        Indicates the behaviour of the payment method token.
        * `SINGLE` - This value must be used if using the Hosted Fields or the Drop-in UI integration types. When creating the payment method token, this option ensures the payment method token is temporary and will be removed once a transaction is executed or after a short period of time.
        * `MULTIPLE` - When creating the payment method token, this indicates it is permanent and can be used to create many transactions.
        * `USE_CARD_NUMBER` - When using the payment method token to transaction process, this indicates to use the card number also known as the PAN or FPAN when bothe the card number and the network token are available.
        * `USE_NETWORK_TOKEN` - When using the payment method token to transaction process, this indicates to use the network token instead of the card number if both are available.
      minLength: 1
      maxLength: 50
      default: MULTIPLE
      example: SINGLE
    fingerprint_mode_PAYMENT_METHODS.fingerprint_mode:
      type: string
      enum:
        - ALWAYS
        - ON_SUCCESS
      description: |
        Indicates whether to execute the fingerprint signature functionality.
        * `ALWAYS` - Always check and create the fingerprint value regardless of the result of the card authorization.
        * `ON_SUCCESS` - Always check and create the fingerprint value when the card authorization is successful.
      minLength: 1
      maxLength: 50
      example: ALWAYS
    name_PAYMENT_METHODS.name:
      type: string
      description: The name of the owner of the payment method. For example the cardholder's name.
      maxLength: 100
      example: John's payment method
    id_PAYMENT_METHODS.payer.id:
      type: string
      description: Unique identifier for the Payer on the Global Payments system.
      minLength: 1
      maxLength: 50
      example: PYR_oOAH6BClraQWS3Qy07dh7tZAN3X2nW
    number_PAYMENT_METHODS.card.number:
      type: string
      description: The card account number used to authorize the transaction. Also known as PAN or FPAN.
      minLength: 1
      maxLength: 50
      example: '4263970000005262'
    expiry_month_PAYMENT_METHODS.card.expiry_month:
      type: string
      description: The 2 digit expiry date month of the card.
      minLength: 2
      maxLength: 2
      example: '05'
    expiry_year_PAYMENT_METHODS.card.expiry_year:
      type: string
      description: The 2 digit expiry date year of the card.
      minLength: 2
      maxLength: 2
      example: '25'
    cvv_PAYMENT_METHODS.card.cvv:
      type: string
      description: The numeric value printed on the physical card.
      example: '852'
    brand_reference_PAYMENT_METHODS.card.brand_reference:
      type: string
      description: The unique reference created by the brands/schemes to uniquely identify the transaction.
      minLength: 1
      maxLength: 50
      example: '000000321000010'
    CreateResponse:
      type: object
      title: CreateResponse
      properties:
        id:
          $ref: '#/components/schemas/id_PAYMENT_METHODS.id'
        time_created:
          $ref: '#/components/schemas/time_created_PAYMENT_METHODS.time_created'
        status:
          $ref: '#/components/schemas/status_PAYMENT_METHODS.status'
        merchant_id:
          $ref: '#/components/schemas/merchant_id_PAYMENT_METHODS.merchant_id'
        merchant_name:
          $ref: '#/components/schemas/merchant_name_PAYMENT_METHODS.merchant_name'
        account_id:
          $ref: '#/components/schemas/account_id_PAYMENT_METHODS.account_id'
        account_name:
          $ref: '#/components/schemas/account_name_PAYMENT_METHODS.account_name'
        fingerprint_presence_indicator:
          $ref: '#/components/schemas/fingerprint_presence_indicator_PAYMENT_METHODS.fingerprint_presence_indicator'
        fingerprint:
          $ref: '#/components/schemas/fingerprint_PAYMENT_METHODS.fingerprint'
        reference:
          $ref: '#/components/schemas/reference_PAYMENT_METHODS.reference'
        usage_mode:
          $ref: '#/components/schemas/usage_mode_PAYMENT_METHODS.usage_mode'
        name:
          $ref: '#/components/schemas/name_PAYMENT_METHODS.name'
        payer:
          type: object
          properties:
            id:
              $ref: '#/components/schemas/id_PAYMENT_METHODS.payer.id'
        card:
          type: object
          properties:
            masked_number_last4:
              $ref: '#/components/schemas/masked_number_last4_PAYMENT_METHODS.card.masked_number_last4'
            expiry_month:
              $ref: '#/components/schemas/expiry_month_PAYMENT_METHODS.card.expiry_month'
            expiry_year:
              $ref: '#/components/schemas/expiry_year_PAYMENT_METHODS.card.expiry_year'
            brand:
              $ref: '#/components/schemas/brand_PAYMENT_METHODS.card.brand'
            network_token:
              $ref: '#/components/schemas/network_token_PAYMENT_METHODS.card.network_token'
            masked_network_token_last4:
              $ref: '#/components/schemas/masked_network_token_last4_PAYMENT_METHODS.card.masked_network_token_last4'
            network_token_expiry_month:
              $ref: '#/components/schemas/network_token_expiry_month_PAYMENT_METHODS.card.network_token_expiry_month'
            network_token_expiry_year:
              $ref: '#/components/schemas/network_token_expiry_year_PAYMENT_METHODS.card.network_token_expiry_year'
            brand_reference:
              $ref: '#/components/schemas/brand_reference_PAYMENT_METHODS.card.brand_reference'
        action:
          type: object
          properties:
            id:
              $ref: '#/components/schemas/id_PAYMENT_METHODS.action.id'
            type:
              $ref: '#/components/schemas/type_PAYMENT_METHODS.action.type'
            time_created:
              $ref: '#/components/schemas/time_created_PAYMENT_METHODS.action.time_created'
            result_code:
              $ref: '#/components/schemas/result_code_PAYMENT_METHODS.action.result_code'
            app_id:
              $ref: '#/components/schemas/app_id_PAYMENT_METHODS.action.app_id'
            app_name:
              $ref: '#/components/schemas/app_name_PAYMENT_METHODS.action.app_name'
    id_PAYMENT_METHODS.id:
      type: string
      description: Unique Global Payments generated id used to reference a stored payment method on the Global Payments system. Often referred to as the payment method token. This value can be used instead of payment method details such as a card number and expiry date.
      maxLength: 50
      example: PMT_f5bbdfde-3010-4802-8f5d-1cdb2a2381c2
    time_created_PAYMENT_METHODS.time_created:
      type: string
      description: Global Payments time indicating when the object was created in ISO-8601 format
      format: date-time
      example: '2021-05-03T21:23:39.718Z'
    status_PAYMENT_METHODS.status:
      type: string
      enum:
        - ACTIVE
        - INACTIVE
        - DELETED
      description: |
        The overall status of the payment method.
          * `ACTIVE` - The entity is ACTIVE and can be used.
          * `INACTIVE` - The entity is INACTIVE and cannot be used."
          * `DELETE` - The status is DELETED. Once returned in an action response for a resource. The resource has been removed from the platform.
      example: ACTIVE
    merchant_id_PAYMENT_METHODS.merchant_id:
      type: string
      description: A unique identifier for the merchant set by Global Payments.
      minLength: 1
      maxLength: 50
      example: MER_c4c0df11039c48a9b63701adeaa296c3
    merchant_name_PAYMENT_METHODS.merchant_name:
      type: string
      description: A meaningful label for the merchant set by Global Payments.
      minLength: 1
      maxLength: 50
      example: Sandbox_merchant_2
    account_id_PAYMENT_METHODS.account_id:
      type: string
      description: A unique identifier for the merchant account set by Global Payments.
      minLength: 1
      maxLength: 50
      example: TRA_86920f927028745yt34d077d88beb29b
    fingerprint_presence_indicator_PAYMENT_METHODS.fingerprint_presence_indicator:
      type: string
      enum:
        - NEW
        - EXISTS
      description: |
        If enabled, this field indicates whether the payment method has been seen before or is new.
        * `EXISTS` - Indicates that the payment method was seen on the platform before by this merchant.
        * `NEW` - Indicates that the payment method was not seen on the platform before by this merchant.
      maxLength: 256
      example: NEW
    fingerprint_PAYMENT_METHODS.fingerprint:
      type: string
      description: 'If enabled, this field contains the unique fingerprint signature for that payment method for that merchant. If the payment method is seen again this same value is generated. For cards the primary account number is checked only. The expiry date or the CVV is not used for this check.'
      maxLength: 256
    masked_number_last4_PAYMENT_METHODS.card.masked_number_last4:
      type: string
      description: Masked number but last 4 digits of card number are visible
      minLength: 4
      maxLength: 4
    brand_PAYMENT_METHODS.card.brand:
      type: string
      enum:
        - VISA
        - MASTERCARD
        - AMEX
        - DINERS
        - DISCOVER
        - JCB
        - CUP
      description: Indicates the card brand that issued the card.
      maxLength: 50
      example: VISA
    network_token_PAYMENT_METHODS.card.network_token:
      type: string
      description: 'The network token,provided by the brands as a more secure alternative to the card number.'
    masked_network_token_last4_PAYMENT_METHODS.card.masked_network_token_last4:
      type: string
      description: Masked network token but last 4 digits of the network token are visible.
      minLength: 4
      maxLength: 4
    network_token_expiry_month_PAYMENT_METHODS.card.network_token_expiry_month:
      type: string
      description: The 2 digit expiry date month of the network token.
      example: '05'
    network_token_expiry_year_PAYMENT_METHODS.card.network_token_expiry_year:
      type: string
      description: The 2 digit expiry date year of the network token.
      example: '25'
    id_PAYMENT_METHODS.action.id:
      type: string
      description: A unique identifier generated by Global Payments to identify an action.
      example: ACT_uzFr7t4VOqxdLDI44hHmXIjHtOOE8d
    type_PAYMENT_METHODS.action.type:
      type: string
      enum:
        - PAYMENT_METHOD_CREATE
        - PAYMENT_METHOD_SINGLE
        - PAYMENT_METHOD_EDIT
        - PAYMENT_METHOD_LIST
        - PAYMENT_METHOD_DELETE
      description: Indicates the specific action taken.
      example: PAYMENT_METHOD_CREATE
    time_created_PAYMENT_METHODS.action.time_created:
      type: string
      description: Global Payments time indicating when the object was created in ISO-8601 format.
      example: '2021-05-03T21:23:39.718Z'
    result_code_PAYMENT_METHODS.action.result_code:
      type: string
      enum:
        - SUCCESS
      description: The result of the action executed.
      example: SUCCESS
    app_id_PAYMENT_METHODS.action.app_id:
      type: string
      description: The id of the app that was used to create the token.
      example: uzFr7t4VOqxdLDI44hHmXIjHtOOE8d
    app_name_PAYMENT_METHODS.action.app_name:
      type: string
      description: The name of the app the user gave to the application.
      example: my_lovely_app
    ListResponse:
      type: object
      title: ListResponse
      properties:
        total_record_count:
          $ref: '#/components/schemas/total_record_count'
        current_page_size:
          $ref: '#/components/schemas/current_page_size'
        merchant_id:
          $ref: '#/components/schemas/merchant_id_PAYMENT_METHODS.merchant_id'
        merchant_name:
          $ref: '#/components/schemas/merchant_name_PAYMENT_METHODS.merchant_name'
        account_id:
          $ref: '#/components/schemas/account_id_PAYMENT_METHODS.account_id'
        account_name:
          $ref: '#/components/schemas/account_name_PAYMENT_METHODS.account_name'
        filter:
          type: object
          properties:
            from_time_created:
              $ref: '#/components/schemas/from_time_created'
            to_time_created:
              $ref: '#/components/schemas/to_time_created'
        paging:
          $ref: '#/components/schemas/Paging'
        payment_methods:
          type: array
          items:
            type: object
            properties:
              id:
                $ref: '#/components/schemas/id_PAYMENT_METHODS.id'
              time_created:
                $ref: '#/components/schemas/time_created_PAYMENT_METHODS.time_created'
              status:
                $ref: '#/components/schemas/status_PAYMENT_METHODS.status'
              reference:
                $ref: '#/components/schemas/reference_PAYMENT_METHODS.reference'
              card:
                type: object
                properties:
                  number_last4:
                    $ref: '#/components/schemas/number_last4_PAYMENT_METHODS.card.number_last4'
                  brand:
                    $ref: '#/components/schemas/brand_PAYMENT_METHODS.card.brand'
                  expiry_month:
                    $ref: '#/components/schemas/expiry_month_PAYMENT_METHODS.card.expiry_month'
                  expiry_year:
                    $ref: '#/components/schemas/expiry_year_PAYMENT_METHODS.card.expiry_year'
                  masked_network_token_last4:
                    $ref: '#/components/schemas/masked_network_token_last4_PAYMENT_METHODS.card.masked_network_token_last4'
                  network_token_expiry_month:
                    $ref: '#/components/schemas/network_token_expiry_month_PAYMENT_METHODS.card.network_token_expiry_month'
                  network_token_expiry_year:
                    $ref: '#/components/schemas/network_token_expiry_year_PAYMENT_METHODS.card.network_token_expiry_year'
        action:
          type: object
          properties:
            id:
              $ref: '#/components/schemas/id_PAYMENT_METHODS.action.id'
            type:
              $ref: '#/components/schemas/type_PAYMENT_METHODS.action.type'
            time_created:
              $ref: '#/components/schemas/time_created_PAYMENT_METHODS.action.time_created'
            result_code:
              $ref: '#/components/schemas/result_code_PAYMENT_METHODS.action.result_code'
            app_id:
              $ref: '#/components/schemas/app_id_PAYMENT_METHODS.action.app_id'
            app_name:
              $ref: '#/components/schemas/app_name_PAYMENT_METHODS.action.app_name'
      x-examples: {}
    total_record_count:
      type: number
      description: 'The total number of records across all pages for the search filter. When searching for a collection of resoures, this is returned on the first page only and when the date range is a month or less.'
      example: 1000
    current_page_size:
      type: number
      description: The total number of records returned on the current page. If current_page_size is less than the page_size using in the querystring then this is the final page for that search.
      example: 564
    from_time_created:
      type: string
      description: |
        The start time to search for in a range, using the resource time_created value.
      format: date
      example: '2022-05-01'
    to_time_created:
      type: string
      description: |
        The end time to search for in a range, using the resource time_created value.
      format: date
      example: '2023-05-01'
    Paging:
      type: object
      title: Paging
      properties:
        page:
          $ref: '#/components/schemas/page.paging.page'
        page_size:
          $ref: '#/components/schemas/page_size.paging.page_size'
        order_by:
          $ref: '#/components/schemas/order_by.paging.order_by'
        order:
          $ref: '#/components/schemas/order.paging.order'
    page.paging.page:
      type: number
      description: 'Indicates the page sequence to return in the response. The number of records presented on each page is determined by page_size field.1 means the first page, 2 the second and so on.'
      default: 1
      example: 1
    page_size.paging.page_size:
      type: number
      description: 'The total number of records to return in a single page for a list. The maximum this value can be is 1000, meaning that the maximum number of records to return in a single request is 1000.'
      minimum: 1
      maximum: 1000
      default: 5
      example: 5
    order_by.paging.order_by:
      type: string
      description: The field to order the list by.
      default: TIME_CREATED
      example: TIME_CREATED
    order.paging.order:
      type: string
      enum:
        - ASC
        - DESC
      description: 'The direction of the ordering of the entire list, ASC or DESC'
      example: ASC
    number_last4_PAYMENT_METHODS.card.number_last4:
      type: string
      description: Last 4 digits of card number
      minLength: 4
      maxLength: 4
    GetResponse:
      type: object
      title: GetResponse
      properties:
        id:
          $ref: '#/components/schemas/id_PAYMENT_METHODS.id'
        time_created:
          $ref: '#/components/schemas/time_created_PAYMENT_METHODS.time_created'
        status:
          $ref: '#/components/schemas/status_PAYMENT_METHODS.status'
        merchant_id:
          $ref: '#/components/schemas/merchant_id_PAYMENT_METHODS.merchant_id'
        merchant_name:
          $ref: '#/components/schemas/merchant_name_PAYMENT_METHODS.merchant_name'
        account_id:
          $ref: '#/components/schemas/account_id_PAYMENT_METHODS.account_id'
        account_name:
          $ref: '#/components/schemas/account_name_PAYMENT_METHODS.account_name'
        reference:
          $ref: '#/components/schemas/reference_PAYMENT_METHODS.reference'
        name:
          $ref: '#/components/schemas/name_PAYMENT_METHODS.name'
        card:
          type: object
          properties:
            number_last4:
              $ref: '#/components/schemas/number_last4_PAYMENT_METHODS.card.number_last4'
            expiry_month:
              $ref: '#/components/schemas/expiry_month_PAYMENT_METHODS.card.expiry_month'
            expiry_year:
              $ref: '#/components/schemas/expiry_year_PAYMENT_METHODS.card.expiry_year'
            brand:
              $ref: '#/components/schemas/brand_PAYMENT_METHODS.card.brand'
            brand_reference:
              $ref: '#/components/schemas/brand_reference_PAYMENT_METHODS.card.brand_reference'
            network_token:
              $ref: '#/components/schemas/network_token_PAYMENT_METHODS.card.network_token'
            network_token_expiry_month:
              $ref: '#/components/schemas/network_token_expiry_month_INSTALLMENTS.payment_method.card.network_token_expiry_month'
            network_token_expiry_year:
              $ref: '#/components/schemas/network_token_expiry_year_PAYMENT_METHODS.card.network_token_expiry_year'
        action:
          type: object
          properties:
            id:
              $ref: '#/components/schemas/id_PAYMENT_METHODS.action.id'
            type:
              $ref: '#/components/schemas/type_PAYMENT_METHODS.action.type'
            time_created:
              $ref: '#/components/schemas/time_created_PAYMENT_METHODS.action.time_created'
            result_code:
              $ref: '#/components/schemas/result_code_PAYMENT_METHODS.action.result_code'
            app_id:
              $ref: '#/components/schemas/app_id_PAYMENT_METHODS.action.app_id'
            app_name:
              $ref: '#/components/schemas/app_name_PAYMENT_METHODS.action.app_name'
      x-examples: {}
    network_token_expiry_month_INSTALLMENTS.payment_method.card.network_token_expiry_month:
      type: string
      description: The 2 digit expiry date month of the network token.
      example: '12'
    PatchRequest:
      type: object
      title: PatchRequest
      properties:
        usage_mode:
          $ref: '#/components/schemas/usage_mode_PAYMENT_METHODS.usage_mode'
        fingerprint_mode:
          $ref: '#/components/schemas/fingerprint_mode_PAYMENT_METHODS.fingerprint_mode'
        name:
          $ref: '#/components/schemas/name_PAYMENT_METHODS.name'
        card:
          type: object
          properties:
            number:
              $ref: '#/components/schemas/number_PAYMENT_METHODS.card.number'
            expiry_month:
              $ref: '#/components/schemas/expiry_month_PAYMENT_METHODS.card.expiry_month'
            expiry_year:
              $ref: '#/components/schemas/expiry_year_PAYMENT_METHODS.card.expiry_year'
            cvv:
              $ref: '#/components/schemas/cvv_PAYMENT_METHODS.card.cvv'
            brand_reference:
              $ref: '#/components/schemas/brand_reference_PAYMENT_METHODS.card.brand_reference'
    PatchResponse:
      type: object
      title: PatchResponse
      properties:
        id:
          $ref: '#/components/schemas/id_PAYMENT_METHODS.id'
        status:
          $ref: '#/components/schemas/status_PAYMENT_METHODS.status'
        fingerprint_presence_indicator:
          $ref: '#/components/schemas/fingerprint_presence_indicator_PAYMENT_METHODS.fingerprint_presence_indicator'
        fingerprint:
          $ref: '#/components/schemas/fingerprint_PAYMENT_METHODS.fingerprint'
        usage_mode:
          $ref: '#/components/schemas/usage_mode_PAYMENT_METHODS.usage_mode'
        name:
          $ref: '#/components/schemas/name_PAYMENT_METHODS.name'
        card:
          type: object
          properties:
            masked_number_last4:
              $ref: '#/components/schemas/masked_number_last4_PAYMENT_METHODS.card.masked_number_last4'
            expiry_month:
              $ref: '#/components/schemas/expiry_month_PAYMENT_METHODS.card.expiry_month'
            expiry_year:
              $ref: '#/components/schemas/expiry_year_PAYMENT_METHODS.card.expiry_year'
            brand:
              $ref: '#/components/schemas/brand_PAYMENT_METHODS.card.brand'
            brand_reference:
              $ref: '#/components/schemas/brand_reference_PAYMENT_METHODS.card.brand_reference'
        action:
          type: object
          properties:
            id:
              $ref: '#/components/schemas/id_PAYMENT_METHODS.action.id'
            type:
              $ref: '#/components/schemas/type_PAYMENT_METHODS.action.type'
            time_created:
              $ref: '#/components/schemas/time_created_PAYMENT_METHODS.action.time_created'
            result_code:
              $ref: '#/components/schemas/result_code_PAYMENT_METHODS.action.result_code'
            app_id:
              $ref: '#/components/schemas/app_id_PAYMENT_METHODS.action.app_id'
            app_name:
              $ref: '#/components/schemas/app_name_PAYMENT_METHODS.action.app_name'
    Detokenize:
      type: object
      title: Detokenize
      properties:
        id:
          $ref: '#/components/schemas/id_PAYMENT_METHODS.id'
        time_created:
          $ref: '#/components/schemas/time_created_PAYMENT_METHODS.time_created'
        status:
          $ref: '#/components/schemas/status_PAYMENT_METHODS.status'
        reference:
          $ref: '#/components/schemas/reference_PAYMENT_METHODS.reference'
        usage_mode:
          $ref: '#/components/schemas/usage_mode_PAYMENT_METHODS.usage_mode'
        name:
          $ref: '#/components/schemas/name_PAYMENT_METHODS.name'
        card:
          type: object
          properties:
            number:
              $ref: '#/components/schemas/number_PAYMENT_METHODS.card.number'
            expiry_month:
              $ref: '#/components/schemas/expiry_month_PAYMENT_METHODS.card.expiry_month'
            expiry_year:
              $ref: '#/components/schemas/expiry_year_PAYMENT_METHODS.card.expiry_year'
            brand:
              $ref: '#/components/schemas/brand_PAYMENT_METHODS.card.brand'
        action:
          type: object
          properties:
            id:
              $ref: '#/components/schemas/id_PAYMENT_METHODS.action.id'
            type:
              $ref: '#/components/schemas/type_PAYMENT_METHODS.action.type'
            time_created:
              $ref: '#/components/schemas/time_created_PAYMENT_METHODS.action.time_created'
            result_code:
              $ref: '#/components/schemas/result_code_PAYMENT_METHODS.action.result_code'
            app_id:
              $ref: '#/components/schemas/app_id_PAYMENT_METHODS.action.app_id'
            app_name:
              $ref: '#/components/schemas/app_name_PAYMENT_METHODS.action.app_name'
    SearchRequest:
      type: object
      title: SearchRequest
      properties:
        account_name:
          $ref: '#/components/schemas/account_name_PAYMENT_METHODS.account_name'
        card:
          type: object
          properties:
            number:
              $ref: '#/components/schemas/number_PAYMENT_METHODS.card.number'
            expiry_month:
              $ref: '#/components/schemas/expiry_month_PAYMENT_METHODS.card.expiry_month'
            expiry_year:
              $ref: '#/components/schemas/expiry_year_PAYMENT_METHODS.card.expiry_year'
    SearchResponse:
      type: object
      title: SearchResponse
      properties:
        total_record_count:
          $ref: '#/components/schemas/total_record_count'
        current_page_size:
          $ref: '#/components/schemas/current_page_size'
        merchant_id:
          $ref: '#/components/schemas/merchant_id_PAYMENT_METHODS.merchant_id'
        merchant_name:
          $ref: '#/components/schemas/merchant_name_PAYMENT_METHODS.merchant_name'
        account_id:
          $ref: '#/components/schemas/account_id_PAYMENT_METHODS.account_id'
        account_name:
          $ref: '#/components/schemas/account_name_PAYMENT_METHODS.account_name'
        filter:
          type: object
          properties:
            account_name:
              $ref: '#/components/schemas/account_name_PAYMENT_METHODS.account_name'
            number:
              $ref: '#/components/schemas/number_PAYMENT_METHODS.card.number'
            expiry_month:
              $ref: '#/components/schemas/expiry_month_PAYMENT_METHODS.card.expiry_month'
            expiry_year:
              $ref: '#/components/schemas/expiry_year_PAYMENT_METHODS.card.expiry_year'
        paging:
          $ref: '#/components/schemas/Paging'
        payment_methods:
          type: array
          items:
            type: object
            properties:
              id:
                $ref: '#/components/schemas/id_PAYMENT_METHODS.id'
              time_created:
                $ref: '#/components/schemas/time_created_PAYMENT_METHODS.time_created'
              status:
                $ref: '#/components/schemas/status_PAYMENT_METHODS.status'
              reference:
                $ref: '#/components/schemas/reference_PAYMENT_METHODS.reference'
              card:
                type: object
                properties:
                  number_last4:
                    $ref: '#/components/schemas/number_last4_PAYMENT_METHODS.card.number_last4'
                  brand:
                    $ref: '#/components/schemas/brand_PAYMENT_METHODS.card.brand'
                  expiry_month:
                    $ref: '#/components/schemas/expiry_month_PAYMENT_METHODS.card.expiry_month'
                  expiry_year:
                    $ref: '#/components/schemas/expiry_year_PAYMENT_METHODS.card.expiry_year'
                  masked_network_token_last4:
                    $ref: '#/components/schemas/masked_network_token_last4_PAYMENT_METHODS.card.masked_network_token_last4'
                  network_token_expiry_month:
                    $ref: '#/components/schemas/network_token_expiry_month_PAYMENT_METHODS.card.network_token_expiry_month'
                  network_token_expiry_year:
                    $ref: '#/components/schemas/network_token_expiry_year_PAYMENT_METHODS.card.network_token_expiry_year'
        action:
          type: object
          properties:
            id:
              $ref: '#/components/schemas/id_PAYMENT_METHODS.action.id'
            type:
              $ref: '#/components/schemas/type_PAYMENT_METHODS.action.type'
            time_created:
              $ref: '#/components/schemas/time_created_PAYMENT_METHODS.time_created'
            result_code:
              $ref: '#/components/schemas/result_code_PAYMENT_METHODS.action.result_code'
            app_id:
              $ref: '#/components/schemas/app_id_PAYMENT_METHODS.action.app_id'
            app_name:
              $ref: '#/components/schemas/app_name_PAYMENT_METHODS.action.app_name'
      x-examples: {}
    from_time_last_updated:
      type: string
      description: |
        The start time to search for in a range, using time_last_updated value.
      format: date-time
    to_time_last_updated:
      type: string
      description: |
        The end time to search for in a range, using time_last_updated value
      format: date-time
    objRequestInvalid_400:
      type: object
      description: Bad Request
      properties:
        error_code:
          type: string
          enum:
            - DUPLICATE_TRANSACTION
            - INVALID_BATCH_ACTION
            - INVALID_REQUEST_DATA
            - INVALID_TRANSACTION_ACTION
            - MANDATORY_DATA_MISSING
            - TRANSACTION_NOT_FOUND
          description: This indicates an issue with the API request.
          example: MANDATORY_DATA_MISSING
        detailed_error_code:
          type: string
          enum:
            - '40016'
          description: Unique reference to identify the error.
          example: '40016'
        detailed_error_description:
          type: string
          description: Unique Text describing the specific error.
          example: Bad track data
    AuthenticationInvalid_401:
      type: object
      description: Not Authenticated
      properties:
        error_code:
          type: string
          enum:
            - NOT_AUTHENTICATED
          description: This action failed as token in the request is not valid.
          example: NOT_AUTHENTICATED
        detailed_error_code:
          type: string
          enum:
            - '40001'
            - '40002'
          description: Unique reference to identify the error.
          example: '40001'
        detailed_error_description:
          type: string
          description: Unique Text describing the specific error.
          example: Invalid Access Token
    NotAuthorized_403:
      type: object
      description: Forbidden
      properties:
        error_code:
          type: string
          enum:
            - ACTION_NOT_AUTHORIZED
          description: This action is not authorized with the credentials being used.
          example: ACTION_NOT_AUTHORIZED
        detailed_error_code:
          type: string
          enum:
            - '40003'
            - '40004'
          description: Unique reference to identify the error.
          example: '40003'
        detailed_error_description:
          type: string
          description: Unique Text describing the specific error.
          example: Permission not enabled to execute action
    ServerError_500:
      type: object
      description: Internal Server Error
      properties:
        error_code:
          type: string
          enum:
            - SYSTEM_ERROR_DOWNSTREAM
          description: This indicates an unexpected issue occurred on the Global Payments system.
          example: SYSTEM_ERROR_DOWNSTREAM
        detailed_error_code:
          type: string
          enum:
            - '50011'
          description: Unique reference to identify the error.
          example: '50011'
        detailed_error_description:
          type: string
          description: Unique Text describing the specific error.
          example: Processor Configuration error
    UnknownServerError_501:
      type: object
      description: Not implemented
      properties:
        error_code:
          type: string
          enum:
            - UNKNOWN_RESPONSE
          description: This is an error not yet handled or mapped properly.
          example: UNKNOWN_RESPONSE
        detailed_error_code:
          type: string
          enum:
            - '50012'
          description: Unique reference to identify the error.
          example: '50012'
        detailed_error_description:
          type: string
          description: 'Unique Text describing the specific error not yet handled.      '
    UnknownPlatformError_502:
      type: object
      description: Bad Gateway
      properties:
        error_code:
          type: string
          enum:
            - UNAUTHORIZED_DOWNSTREAM
          description: This is an error indicating there was an issue connecting to a partner system..
          example: UNAUTHORIZED_DOWNSTREAM
        detailed_error_code:
          type: string
          enum:
            - '50002'
          description: Unique reference to identify the error.
          example: '50002'
        detailed_error_description:
          type: string
          description: Authentication error—Verify and correct credentials.
    ServerTimeout_504:
      type: object
      description: Timeout
      properties:
        error_code:
          type: string
          enum:
            - TIMEOUT_DOWNSTREAM
          description: This is an error indicating there was a timeout issue to another  system.
          example: TIMEOUT_DOWNSTREAM
        detailed_error_code:
          type: string
          enum:
            - '50008'
          description: Unique reference to identify the error.
          example: '50008'
        detailed_error_description:
          type: string
          description: No response from payment method provider.
security:
  - bearerAuth: []
